name: Rust CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/main.rs'
      - 'src/lib.rs'
      - 'lib/*'
      - 'cargo.toml'
      - 'cargo.lock'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
